#OFICIAL
#app_key: yvwtuws7p6nkgxw
#app_secret: yp7p749yjuztrjr
#access_token: l5jstljbw6uzjwsx
#access_token_secret: 9eyw1lqwpx25ry0
#user_id: 268851359
#access_type: "app_folder"


#PRUEBAS
app_key: 9aww53mg1bmbqb2
app_secret: o53lfcjr68h7t5t
access_token: vkrs197r2rglicmu
access_token_secret: 3wlinpjzzyg32hk
user_id: 268851359
access_type: "app_folder"